/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { useTexture } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/man/model.gltf')
  const [ao, normal, map, roughness] = useTexture([
    '/man/shirt/Shirt_AmbientOcclusion.PNG', 
    '/man/shirt/Shirt_Normal.PNG', 
    '/man/shirt/ShirtBlack_Base_Color.PNG', 
    '/man/shirt/ShirtBlack_Roughness.PNG', 
  ])
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.OutfitBoots.geometry} material={materials['1011_Boots.001']} />
      <mesh geometry={nodes.OutfitLegs.geometry} material={materials['1002_Pants.001']} />
      <mesh geometry={nodes.OutfitTorso001.geometry} material={materials['1001_Shirt.001']}>
        <meshStandardMaterial
          map={map}
          normalMap={normal}
          aoMap={ao}
          roughnessMap={roughness}
          map-flipY={false}
          normalMap-flipY={false}
          roughnessMap-flipY={false}
          aoMap-flipY={false}
        />
      </mesh>
      <mesh geometry={nodes.OutfitTorso001_1.geometry} material={materials['1003_Facecover.001']} />
      <mesh geometry={nodes.OutfitTorso001_2.geometry} material={materials['1012_Hoodie.001']} />
      <mesh geometry={nodes.OutfitTorso001_3.geometry} material={materials['1003_Shoulders.001']} />
    </group>
  )
}

useGLTF.preload('/man/model.gltf')
